### ISSUE TITLE
Nest Skills in Jsonresume?

### ISSUE THREAD

**Issue by notflip** [Jac21/SkillSet#3]
Can't seem to find how to do that in the docs, do you have any idea?

**Comment by Jac21** [comment]
I seem to recall being able to fiddle enough with the online editor over at http://registry.jsonresume.org/ to get that working in some fashion long ago, however, this doesn't seem to be the case anymore upon further inspection. Perhaps I was taking advantage of some undefined behavior, or perhaps they've tightened up the schema to disallow that since then, but you raise a very good point in terms of getting that hierarchy conveyed. 

If you're looking to do so in a static manner for this particular visualization, as a proof-of-concept, you can simply update the CSV output like so, wherein a target node is used again as a source node, to get the output looking exactly how you want it: 

![image](https://user-images.githubusercontent.com/1449455/49551657-aec95800-f8b5-11e8-9c3d-8b6e57566c13.png)

I'll look into seeing if I can handle some custom-schema that makes sense to me on my end and doesn't break usages of other tools, but I'd definitely raise an issue over at https://github.com/jsonresume if you haven't already. I'm definitely interested, as well.

**Comment by Jac21** [comment]
@notflip, is there anything else I can help out with to get this issue closed out?
